### ISSUE TITLE
AOTF code for In vivo SPIM

### ISSUE THREAD

**Issue by aqeisari** [ludovicosilvestri/Giorgio#62]
The code works without any error. The line status is also showing the expected information but the beam does not pass through the AOTF. I have tried to unplug the internal control but still the same result. Do you have any suggestion what would be problem?

**Comment by TommasoA** [comment]
There is a VI to control the AOTF without imaging mode spin it calls AOTF_in_vivo spin.
Maybe there are some error of communication between the pc and the RS232 of the AOTF in imaging mode.
This project works properly. 
Tommi
